name: CI
on:
  push:
    branches: [  nathan-develop  ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.4
      with:
        java-version: '13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r side_prohect/requirement.txt
